//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projects
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAJOR
    {
        public int Id { get; set; }
        public int SchoolId { get; set; }
        public string Major1 { get; set; }
        public Nullable<decimal> GPA { get; set; }
        public string Graduated { get; set; }
        public Nullable<System.DateTime> Graduated_Date { get; set; }
    
        public virtual SCHOOL SCHOOL { get; set; }
    }
}
