//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projects
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StocksEntities : DbContext
    {
        public StocksEntities()
            : base("name=StocksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Preference> Preferences { get; set; }
        public virtual DbSet<StockPreference> StockPreferences { get; set; }
        public virtual DbSet<Stock> Stocks { get; set; }
        public virtual DbSet<SubPreference> SubPreferences { get; set; }
    }
}
