//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projects
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockPreference
    {
        public string Stock { get; set; }
        public int Preference { get; set; }
        public string Value { get; set; }
    
        public virtual Preference Preference1 { get; set; }
        public virtual Stock Stock1 { get; set; }
    }
}
